-- MySQL Script generated by MySQL Workbench
-- Thu Apr  5 12:08:14 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`family` (
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `account` INT NOT NULL,
  `phonenum` VARCHAR(45) NOT NULL,
  `familycol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dump_station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dump_station` (
  `station_id` VARCHAR(30) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `garbage_type` INT NOT NULL,
  PRIMARY KEY (`station_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`garbage_collector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`garbage_collector` (
  `collector_id` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `threshold` FLOAT NOT NULL,
  `damage_capacity` INT NOT NULL,
  `organ_capacity` INT NOT NULL,
  `inogran_capacity` INT NOT NULL,
  `is_wrong` INT NOT NULL,
  PRIMARY KEY (`collector_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`garbage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`garbage` (
  `garbage_id` VARCHAR(30) NOT NULL,
  `garbage_type` INT NOT NULL,
  `state` INT NOT NULL,
  `dump_station_id` VARCHAR(30) NOT NULL,
  `username` VARCHAR(30) NOT NULL,
  `garbage_collector_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`garbage_id`),
  INDEX `fk_garbage_dump_station1_idx` (`dump_station_id` ASC),
  INDEX `fk_garbage_family1_idx` (`username` ASC),
  INDEX `fk_garbage_garbage_collector1_idx` (`garbage_collector_id` ASC),
  CONSTRAINT `fk_garbage_dump_station1`
    FOREIGN KEY (`dump_station_id`)
    REFERENCES `mydb`.`dump_station` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_garbage_family1`
    FOREIGN KEY (`username`)
    REFERENCES `mydb`.`family` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_garbage_garbage_collector1`
    FOREIGN KEY (`garbage_collector_id`)
    REFERENCES `mydb`.`garbage_collector` (`collector_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`car_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`car_center` (
  `car_center_id` VARCHAR(30) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`car_center_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crew_center`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`crew_center` (
  `crew_center_id` VARCHAR(30) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`crew_center_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`crew`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`crew` (
  `crew_id` VARCHAR(30) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `phonenum` VARCHAR(45) NOT NULL,
  `salary` INT NOT NULL,
  `crew_type` INT NOT NULL,
  `crew_center_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`crew_id`),
  INDEX `fk_crew_crew_center1_idx` (`crew_center_id` ASC),
  CONSTRAINT `fk_crew_crew_center1`
    FOREIGN KEY (`crew_center_id`)
    REFERENCES `mydb`.`crew_center` (`crew_center_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`car` (
  `car_id` VARCHAR(30) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `car_state` VARCHAR(45) NOT NULL,
  `garbage_type` INT NOT NULL,
  `car_center_id` VARCHAR(30) NOT NULL,
  `crew_id` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`car_id`),
  INDEX `fk_car_car_center1_idx` (`car_center_id` ASC),
  INDEX `fk_car_crew1_idx` (`crew_id` ASC),
  CONSTRAINT `fk_car_car_center1`
    FOREIGN KEY (`car_center_id`)
    REFERENCES `mydb`.`car_center` (`car_center_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_crew1`
    FOREIGN KEY (`crew_id`)
    REFERENCES `mydb`.`crew` (`crew_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
